#!/bin/sh /etc/rc.common
# NVRAM setup
#
# This file handles the NVRAM quirks of various hardware of the bcm53xx target.

START=02

clear_partialboots() {
	# clear partialboots

	case $(board_name) in
		linksys,ea9200|\
		linksys,panamera)
			COMMIT=1
			nvram set partialboots=0
			;;
	esac
}

set_wireless_led_behaviour() {
	# set Broadcom wireless LED behaviour for both radios
	# 0:ledbh9 -> Behaviour of 2.4GHz LED of Broadcom BCM4366
	# 1:ledbh9 -> Behaviour of 5GHz LED of Broadcom BCM4366
	# 0:ledbh10 -> Behaviour of 2.4GHz LED of Broadcom BCM43602
	# 1:ledbh10 -> Behaviour of 5GHz LED of Broadcom BCM43602
	# 0x7 makes the wireless LEDs on, when radios are enabled, and blink when there's activity

	case $(board_name) in
		asus,rt-ac3100|\
		asus,rt-ac5300|\
		asus,rt-ac88u)
			COMMIT=1
			nvram set 0:ledbh9=0x7 set 1:ledbh9=0x7
			;;
		asus,rt-ac3200)
			COMMIT=1
			nvram set 0:ledbh10=0x7 set 1:ledbh10=0x7
			;;
		netgear,r8000)
			COMMIT=1
			# All three radios are BCM43602 (devid 0x43bc/0x43bb, see
			# set_bcm43602_variables below) -> ledbh10, one entry per
			# SROM-prefixed radio slot (0/1/2).
			#
			# NOTE: on this board the visible front-panel 2.4GHz/5GHz-1/
			# 5GHz-2 LEDs are wired to the main SoC's ChipCommon GPIOs
			# and driven as plain Linux gpio-leds (see
			# target/linux/bcm53xx/base-files/etc/board.d/01_leds and
			# v2-staging/leds/notes.md) -- confirmed via the running
			# unit's live device tree. Setting the radio-local ledbh10
			# behaviour bit here is for parity with the other BCM43602
			# boards in this file and in case the wifi chip itself also
			# drives a chip-local LED GPIO on this board revision; it
			# has no confirmed effect on the front-panel LEDs and is
			# not required for them to work.
			nvram set 0:ledbh10=0x7 set 1:ledbh10=0x7 set 2:ledbh10=0x7
			;;
	esac
}

set_bcm43602_variables() {
	# set variables needed for Broadcom BCM43602

	case $(board_name) in
		asus,rt-ac3200)
			COMMIT=1

			# radio 0 (5 GHz)
			nvram set devpath0=pcie/1/3
			nvram set 0:devpath0=sb/1/
			nvram set 0:devid=0x43bc
			nvram set 0:sromrev=11
			nvram set 0:boardflags=0x30040000

			# radio 1 (2.4 GHz)
			nvram set devpath1=pcie/1/4
			nvram set 1:devpath1=sb/1/
			nvram set 1:devid=0x43bb
			nvram set 1:boardrev=0x1421
			nvram set 1:sromrev=11
			nvram set 1:boardflags=0x20001000

			# radio 2 (5 GHz)
			nvram set devpath2=pcie/2/1
			nvram set 2:devpath2=sb/1/
			nvram set 2:devid=0x43bc
			nvram set 2:sromrev=11
			nvram set 2:boardflags=0x30040000
			;;

		netgear,r8000)
			COMMIT=1

			# radio 0 (5 GHz) - BCM43602
			nvram set devpath0=pcie/1/1
			nvram set 0:devpath0=sb/1/
			nvram set 0:devid=0x43bc
			nvram set 0:boardrev=0x1421
			nvram set 0:sromrev=11
			nvram set 0:boardflags=0x30008000
			nvram set 0:boardflags2=0x2

			# radio 1 (2.4 GHz) - BCM43602
			nvram set devpath1=pcie/2/3
			nvram set 1:devpath1=sb/1/
			nvram set 1:devid=0x43bb
			nvram set 1:boardrev=0x1421
			nvram set 1:sromrev=11
			nvram set 1:boardflags=0x1000
			nvram set 1:boardflags2=0x2

			# radio 2 (5 GHz) - BCM43602
			nvram set devpath2=pcie/2/4
			nvram set 2:devpath2=sb/1/
			nvram set 2:devid=0x43bc
			nvram set 2:boardrev=0x1421
			nvram set 2:sromrev=11
			nvram set 2:boardflags=0x10000000
			nvram set 2:boardflags2=0x2
			;;
	esac
}

boot() {
	. /lib/functions.sh

	clear_partialboots
	set_wireless_led_behaviour
	set_bcm43602_variables

	[ "$COMMIT" = "1" ] && nvram commit
}
